apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: pitang-teste-tecnico
spec:
  selector:
    app: pitang-teste-tecnico
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort